// Generates the version constant from package.json (run on build/typecheck) — the same
// drift-proof pattern as packages/cli/scripts/generate-kit-versions.mjs. Keeps the
// "Version Packages" PR green: the changesets bot bumps package.json, the constant follows
// at the next build instead of being hand-maintained.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const { version } = JSON.parse(readFileSync(join(pkgRoot, 'package.json'), 'utf8'));

writeFileSync(
  join(pkgRoot, 'src', 'version.generated.ts'),
  `// Generated by scripts/generate-version.mjs — do not edit by hand.
export const CORE_VERSION = '${version}' as const;
`,
);
