// Root storefront layout (route group (frontend)). The Payload admin lives in
// its own route group (payload) with its own layout — so there's no root app/layout,
// and each group renders its own <html> (the Payload 3 + Next pattern).
import type { ReactNode } from 'react';
import type { Metadata } from 'next';
import '../globals.css';
import { siteConfig } from '@/site.config';
import { baseUrl, siteName } from '@/lib/site';
import { registerSlots } from '@/lib/slots';
import { Slot } from '@vitrine-kit/core/react';
import { SlotsProvider } from '@/components/SlotsProvider';
import { SiteHeader } from '@/components/layout/SiteHeader';
import { SiteFooter } from '@/components/layout/SiteFooter';

// Register installed features' slots for SSR (lib/slots.ts is generated by the CLI).
// SlotsProvider re-runs the same registration in the browser so <Slot> hydrates.
registerSlots();

export const metadata: Metadata = {
  metadataBase: new URL(baseUrl),
  title: { default: siteName, template: `%s · ${siteName}` },
};

export default function FrontendLayout({ children }: { children: ReactNode }) {
  return (
    <html lang={siteConfig.i18n.defaultLocale}>
      <body className="min-h-screen bg-bg font-sans text-fg antialiased">
        <SlotsProvider>
          <Slot name="global.banner-top" />
          <SiteHeader />
          <main className="mx-auto w-full max-w-container px-gutter py-section">{children}</main>
          <SiteFooter />
          <Slot name="global.body-end" />
        </SlotsProvider>
      </body>
    </html>
  );
}
