// Generated by scripts/generate-kit-versions.mjs — do not edit by hand.
export const KIT_VERSION = '0.3.1';
/** Contract API semver written to vitrine.json (stable until a breaking contract change). */
export const CONTRACTS_VERSION = '1.0.0';
export const CONTRACTS_RANGE = '^1.0.0';
export const CORE_RANGE = '^0.2.0';
export const BLUEPRINT_RANGE = '^0.2.0';
