// The client's Payload 3 config. Collections are assembled by the blueprint (base +
// additive feature extensions, lib/blueprint.ts — generated by the CLI). The DB is
// chosen zero-config (db.ts → §18.1). onInit runs the demo seed and boot admin.
// Email adapter is optional — present when the `email` feature is installed.
// Localization mirrors site.config i18n when more than one locale is configured.
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { CollectionConfig } from 'payload';
import { buildConfig } from 'payload';
import { lexicalEditor } from '@payloadcms/richtext-lexical';
import sharp from 'sharp';
import { collections } from './lib/blueprint.js';
import { resolveDbAdapter } from './lib/adapter/db.js';
import { seedDemo } from './lib/seed/run.js';
import { ensureDevAdmin } from './lib/seed/admin.js';
import { siteConfig } from './site.config.js';

const dirname = path.dirname(fileURLToPath(import.meta.url));

// Empty string from `cp .env.example .env` must not count as set (?? only skips null/undefined).
const payloadSecret = process.env.PAYLOAD_SECRET?.trim() || undefined;
if (!payloadSecret && process.env.NODE_ENV === 'production') {
  // No silent fallback to the dev secret in production (mirrors the Vendure DATABASE_URL guard).
  throw new Error('[vitrine] PAYLOAD_SECRET is required in production');
}

async function loadEmailAdapter(): Promise<unknown> {
  try {
    const mod = await import('./lib/email/adapter.js');
    return await mod.resolveEmailAdapter();
  } catch {
    return undefined;
  }
}

const email = await loadEmailAdapter();

const locales = siteConfig.i18n.locales.filter(Boolean);
const localization = {
  locales: locales.length > 0 ? locales : ['en'],
  defaultLocale: siteConfig.i18n.defaultLocale || locales[0] || 'en',
  fallback: true,
};

export default buildConfig({
  admin: {
    user: 'users',
    importMap: { baseDir: path.resolve(dirname) },
  },
  collections: collections as unknown as CollectionConfig[],
  editor: lexicalEditor(),
  secret: payloadSecret ?? 'dev-secret-change-me',
  db: await resolveDbAdapter(),
  sharp,
  localization,
  ...(email ? { email: email as never } : {}),
  typescript: { outputFile: path.resolve(dirname, 'payload-types.ts') },
  async onInit(payload) {
    await seedDemo(payload);
    await ensureDevAdmin(payload);
  },
});
